name: Build and Deploy to AWS ECR

on:
    push:
        branches:
        - main
jobs:
    build:
        runs-on: ubuntu-latest
        environment: awscontainerizedapp
        steps:
        - name : Checkout code
          uses: actions/checkout@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Log in to Amazon ECR
          uses: aws-actions/amazon-ecr-login@v1
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
        - name: Build and push Docker image
          uses: docker/build-push-action@v2
          with:
            context: .
            file: Dockerfile
            push: true
            tags: ${{ secrets.ECR_REPOSITORY }}:latest
        - name: Deploy to AWS ECS
          uses: aws-actions/amazon-ecs-deploy-task-definition@v1
          with:
            task-definition: ecs-task-definition.json
            service: my-ecs-service
            cluster: my-ecs-cluster
            wait-for-service-stability: true